Document: qcheckers
Title: Debian qcheckers Manual
Author: <insert document author here>
Abstract: This manual describes what qcheckers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qcheckers/qcheckers.sgml.gz

Format: postscript
Files: /usr/share/doc/qcheckers/qcheckers.ps.gz

Format: text
Files: /usr/share/doc/qcheckers/qcheckers.text.gz

Format: HTML
Index: /usr/share/doc/qcheckers/html/index.html
Files: /usr/share/doc/qcheckers/html/*.html
